-- snowflake_db_web_schema: orders
select
_FIVETRAN_ID, 
ORDER_ID, 
SHIPPING_ADDRESS, 
TAX_RATE, 
PAYMENT_INFO, 
ORDER_AT AS ORDER_AT_TS, 
STATE, 
SESSION_ID, 
CAST(REPLACE(SHIPPING_COST, 'USD ', '') AS FLOAT) AS SHIPPING_COST, 
CLIENT_NAME, 
PAYMENT_METHOD, 
PHONE, 
_FIVETRAN_DELETED, 
_FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
from {{  source('snowflake_db_web_schema', 'orders')}}